# Generated by Django 5.0.4 on 2024-04-24 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Zagolovok')),
                ('text', models.TextField(verbose_name='Tekst Novosti')),
                ('image', models.ImageField(upload_to='post_img/', verbose_name='Kartinka Posta')),
                ('slug', models.SlugField(unique=True, verbose_name='Ssilka')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data sozdaniya posta')),
            ],
        ),
    ]
